### ISSUE TITLE
install error：ModuleNotFoundError: No module named 'Cython'

### ISSUE THREAD

**Issue by sin-en-2009** [brmmm3/fastthreadpool#1]
**When I installed the module, I reported the following error**
Whether a CPython module must be installed to use？

Collecting fastthreadpool
  Downloading https://files.pythonhosted.org/packages/7d/88/aa72ec6fcbf37c81e6546f1f7febe5cba7a6a783db6bf643d03e20649c3f/fastthreadpool-1.5.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\samsung\AppData\Local\Temp\pycharm-packaging\fastthreadpool\setup.py", line 20, in <module>
        from Cython.Distutils import build_ext
    ModuleNotFoundError: No module named 'Cython'

**Comment by brmmm3** [comment]
Cython module must be installed first. I have to add a requirements.txt so that cython is installed automatically. Thx for reporting.

**Comment by brmmm3** [comment]
Should be fixed in latest version.
